@host = http://localhost:5000/api

# @name GetAccessCookie
// @no-log
POST {{host}}/authentication/get-access-cookie HTTP/2.0
Content-Type: application/json

{
    "userName": "ngokhanhhuyy",
    "password": "Huyy47b1"
}

###
@accessCookie = {{GetAccessCookie.response.headers.Set-Cookie}}

###
# @name UserList
// @no-log
GET {{host}}/users HTTP/2.0
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name CustomerList
// @no-log
GET {{host}}/customers?sortByFieldName=CreatedDateTime&sortByAscending=False&page=1
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name CustomerDetail
GET {{host}}/customers/102
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name CustomerCreate
POST {{host}}/customers
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "firstName": "Ngô",
    "middleName": "Khánh",
    "lastName": "Huy",
    "nickName": "Huy Nino",
    "gender": "Male",
    "birthday": "1997-08-30",
    "phoneNumber": "09037632117",
    "zaloNumber": "09037632117",
    "facebookUrl": "https://facebook.com/huy.nino.97",
    "email": "ngokhanhhuyy@gmail.com",
    "address": "173 Lý Thái Tổ, phường Buôn Ma Thuột 2",
    "note": null,
    "introducerId": null
}

###
# @name CustomerUpdate
PUT {{host}}/customers/101
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "firstName": "Ngô",
    "middleName": "Khánh",
    "lastName": "Huy",
    "nickName": "Huy Nino",
    "gender": "Male",
    "birthday": "2025-08-30",
    "phoneNumber": "09037632117",
    "zaloNumber": "09037632117",
    "facebookUrl": "https://facebook.com/huy.nino.97",
    "email": "ngokhanhhuyy@gmail.com",
    "address": "173 Lý Thái Tổ, phường Buôn Ma Thuột 2",
    "note": null,
    "introducerId": null
}

###
# @name CustomerDelete
DELETE {{host}}/customers/235
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name CustomerNewStatistics
// @no-log
GET {{host}}/customers/newStatistics
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name ProductList
// @no-log
GET {{host}}/products
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name ProductDetail
// @no-log
GET {{host}}/products/1
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name ProductCategoryAll
GET {{host}}/products/categories
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name ProductCategoryDetail
GET {{host}}/products/categories/ac834dc6-1995-430a-b109-e04419c0026c
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name ProductCategoryUpdate
PUT {{host}}/products/categories/5e5e7af4-856a-4c7d-81a9-b728f2137aec
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "name": "Beauty"
}

###
# @name ProductCategoryDelete
DELETE {{host}}/products/categories/006ee6ee-d203-46af-ad1d-1669315357ed
Cookie: {{accessCookie}}

###
# @name SupplyList
// @no-log
GET {{host}}/supply
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name TreatmentList
GET {{host}}/treatment
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "ignoreMonthYear": true
}

###
# @name DebtIncurrenceList
GET {{host}}/debtIncurrence
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name DebtIncurrenceCreate
POST {{host}}/debtIncurrence
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "amount": 2000000,
    "note": null,
    "incurredDateTime": null,
    "customersId": 8
}

###
# @name DebtPaymentList
GET {{host}}/debtPayment?sortingByField=StatsDateTime&sortingByAscending=False
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name DebtPaymentDetail
GET {{host}}/debtPayment/37
Content-Type: application/json
Cookie: {{accessCookie}}


###
# @name DebtPaymentCreate
POST {{host}}/debtPayment
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "amount": 2000000,  
    "note": null,
    "statsDateTime": null,
    "customersId": 10
}

###
# @name DebtPaymentUpdate
PUT {{host}}/debtPayment/39
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "amount": 1900000,  
    "note": null,
    "statsDateTime": null,
    "customersId": 2,
    "updatedReason": "Removed note"
}

###
# @name PhotoGetMultipleByProductIds
# @no-log
GET {{host}}/photos
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-MonthlyDetail
# @no-log
GET {{host}}/stats/monthly?recordedYear=2025&recordedMonth=4
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-LastestMonthlyBasic
# @no-log
GET {{host}}/stats/lastestMonthlyBasic?monthCount=1&includeThisMonth=false
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-LastestDailyBasic
# @no-log
GET {{host}}/stats/lastestDailyBasic?dayCount=61&includeToday=false
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-TopSoldProductList
# @no-log
GET {{host}}/stats/topSoldProductList?creteria=Quantity
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-TopPurchasedCustomerList
# @no-log
GET {{host}}/stats/topPurchasedCustomerList?creteria=PurchasedTransactionCount
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-LastestTransactions
# @no-log
GET {{host}}/stats/lastestTransactions
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-StatsDateOptions
# @no-log
GET {{host}}/stats/statsDateOptions
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name HealthCheck
// @no-log
GET {{host}}/healthcheck/ping
Content-Type: application/json

###
# @name ResourceAccess-AccessingUsers
// @no-log
GET {{host}}/resourceAccess/accessingUsers?type=Customer&primaryId=11&mode=0
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name ResourceAccess-Status
// @no-log
GET {{host}}/resourceAccess/status
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Metadata
GET {{host}}/metadata
Cookie: {{accessCookie}}