global using System.Text.Json;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.SignalR;
global using NATSInternal.Extensions;
global using NATSInternal.Hubs;
global using NATSInternal.Hubs.Notifier;
global using NATSInternal.Hubs.ResourceAccess;
global using NATSInternal.Core;
global using NATSInternal.Core.Constants;
global using NATSInternal.Core.Dtos;
global using NATSInternal.Core.Enums;
global using NATSInternal.Core.Exceptions;
global using NATSInternal.Core.Interfaces;
global using NATSInternal.Validation;
global using NATSInternal.Validation.Validators;

global using IAuthorizationService = NATSInternal.Core.Interfaces.IAuthorizationService;
global using FluentValidation;
global using FluentValidation.Results;
global using ValidationResult = FluentValidation.Results.ValidationResult;
global using ValidationException = System.ComponentModel.DataAnnotations.ValidationException;
