@host = http://localhost:5000/api

# @name GetAccessCookie
// @no-log
POST {{host}}/authentication/get-access-cookie HTTP/2.0
Content-Type: application/json

{
    "userName": "ngokhanhhuyy",
    "password": "Huyy47b1"
}

###
@accessCookie = {{GetAccessCookie.response.headers.Set-Cookie}}

###
# @name UserGetList
// @no-log
GET {{host}}/users HTTP/2.0
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name CustomerList
// @no-log
GET {{host}}/customer?sortingByFieldName=LastName&sortingByAscending=False&page=1
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name CustomerDetail
GET {{host}}/customer/22ce8b27-3729-4c9c-900a-5479c9e1ab93
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name CustomerNewStatistics
// @no-log
GET {{host}}/customers/newStatistics
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name ProductList
// @no-log
GET {{host}}/products
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name ProductDetail
// @no-log
GET {{host}}/productsde91b603-a202-4adc-a684-2c646e3f2f8b
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name SupplyList
// @no-log
GET {{host}}/supply
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name TreatmentList
GET {{host}}/treatment
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "ignoreMonthYear": true
}

###
# @name DebtIncurrenceList
GET {{host}}/debtIncurrence
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name DebtIncurrenceCreate
POST {{host}}/debtIncurrence
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "amount": 2000000,
    "note": null,
    "incurredDateTime": null,
    "customersId": 8
}

###
# @name DebtPaymentList
GET {{host}}/debtPayment?sortingByField=StatsDateTime&sortingByAscending=False
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name DebtPaymentDetail
GET {{host}}/debtPayment/37
Content-Type: application/json
Cookie: {{accessCookie}}


###
# @name DebtPaymentCreate
POST {{host}}/debtPayment
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "amount": 2000000,  
    "note": null,
    "statsDateTime": null,
    "customersId": 10
}

###
# @name DebtPaymentUpdate
PUT {{host}}/debtPayment/39
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "amount": 1900000,  
    "note": null,
    "statsDateTime": null,
    "customersId": 2,
    "updatedReason": "Removed note"
}

###
# @name Stats-MonthlyDetail
# @no-log
GET {{host}}/stats/monthly?recordedYear=2025&recordedMonth=4
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-LastestMonthlyBasic
# @no-log
GET {{host}}/stats/lastestMonthlyBasic?monthCount=1&includeThisMonth=false
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-LastestDailyBasic
# @no-log
GET {{host}}/stats/lastestDailyBasic?dayCount=61&includeToday=false
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-TopSoldProductList
# @no-log
GET {{host}}/stats/topSoldProductList?creteria=Quantity
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-TopPurchasedCustomerList
# @no-log
GET {{host}}/stats/topPurchasedCustomerList?creteria=PurchasedTransactionCount
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-LastestTransactions
# @no-log
GET {{host}}/stats/lastestTransactions
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Stats-StatsDateOptions
# @no-log
GET {{host}}/stats/statsDateOptions
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name HealthCheck
// @no-log
GET {{host}}/healthcheck/ping
Content-Type: application/json

###
# @name ResourceAccess-AccessingUsers
// @no-log
GET {{host}}/resourceAccess/accessingUsers?type=Customer&primaryId=11&mode=0
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name ResourceAccess-Status
// @no-log
GET {{host}}/resourceAccess/status
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name Metadata
GET {{host}}/metadata
Cookie: {{accessCookie}}