global using System.Reflection;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.DependencyInjection;

global using MySqlConnector;
global using NATSInternal.Core.Constants;
global using NATSInternal.Core.Contracts;
global using NATSInternal.Core.DbContext;
global using NATSInternal.Core.Dtos;
global using NATSInternal.Core.Enums;
global using NATSInternal.Core.Entities;
global using NATSInternal.Core.Exceptions;
global using NATSInternal.Core.Extensions;
global using NATSInternal.Core.Handlers;
global using NATSInternal.Core.Interfaces;
global using NATSInternal.Core.Interfaces.Dtos;
global using NATSInternal.Core.Interfaces.Entities;
global using NATSInternal.Core.Interfaces.Services;
global using NATSInternal.Core.Identity;
global using NATSInternal.Core.Localization;
global using NATSInternal.Core.Services;
global using NATSInternal.Core.Utilities;
global using NATSInternal.Core.Validation;

global using FluentValidation;
global using ValidationException = System.ComponentModel.DataAnnotations.ValidationException;
global using ImageMagick;
global using Bogus;